FROM node:16-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ENV HOST=0.0.0.0
ENV CHOKIDAR_USEPOLLING=true
ENV WDS_SOCKET_PORT=3000
ENV WATCHPACK_POLLING=true

EXPOSE 3000

CMD ["npm", "start"]
